# NOTE: update this with your service name
service: api-gateway-serverless

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack
  - serverless-offline

# serverless-webpack configuration
# Enable auto-packing of external modules
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-west-2
  environment: ${file(env.yml):${self:provider.stage}}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
  flights:
    handler: flights.main
    events:
      - http:
          path: flights
          method: get
          cors: true